modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "extendedgears"
version = "${version}"
displayName = "Extended Cogwheels"
authors = "Rabbitminers"
description = '''
A small mod adding more cogs to the create mod
'''
logoFile = "icon.png"

[[dependencies.extendedgears]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedgears]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedgears]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="AFTER"
side="BOTH"

[[dependencies.extendedgears]]
modId="kubejs"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"