modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId= "extendedgears" #mandatory

# If you prefer this can be manually set
version="${file.jarVersion}" #mandatory

# TODO: Add your mods name
displayName="Extended Cogs" #mandatory

logoFile="extendedgears.png" #optional

credits="Rabbitminers" #optional

# TODO: Add your name here
authors="yourname" #optional
# TODO: Describe your mod
description='''
A small addon to create adding more types of cogs
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.extendedgears]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.extendedgears]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.g,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.extendedgears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
